openapi: 3.0.1
info:
  title: UserService API
  description: UserService API documentation
  version: 1.0
paths:
  /users/secured:
    get:
      summary: "Привіт Світ"
      description: "Цей ендпоінт повертає привітальне повідомлення"
      responses:
        "200":
          description: "Успішна відповідь"
          content:
            application/json:
              schema:
                type: string
